export enum QueueProcessorMethodsNames {
  COLLECT_NFT = 'COLLECT_NFT',
  UPDATE_OFFERS = 'UPDATE_OFFERS',
  COLLECT_COLLECTIONS = 'COLLECT_COLLECTIONS',
  READ_COLLECTION_ADDRESSES = 'READ_COLLECTION_ADDRESSES',
  COLLECT_BLOCKCHAIN_EVENTS = 'collectBlockchainEvents',
}
